apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uf 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: splunk
        role: uf
        tier: uf
    spec:
      hostname: uf
      containers:
        - name: uf
          image: splunk/universalforwarder:8.0.0
          imagePullPolicy: Always
          env:
            - name: SPLUNK_USER
              value: root
            - name: SPLUNK_PASSWORD
              value: helloworld
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_STANDALONE_URL
              value: standalone
            - name: DEBUG
              value: "true"
          volumeMounts: 
            - name: splunk-uf-data
              mountPath: /opt/splunk/var
            - name: splunk-uf-config
              mountPath: /opt/splunk/etc
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/snap/microk8s/common/var/lib/docker/containers/ 
              readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/snap/microk8s/common/var/lib/docker/containers/
        - name: splunk-uf-config
          emptyDir: {}
        - name: splunk-uf-data
          emptyDir: {}
