##---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sck-splunk-kubernetes-metrics
  labels:
    app: splunk-kubernetes-metrics
    chart: splunk-kubernetes-metrics-1.1.0
    release: sck
    heritage: Tiller
data:
  fluent.conf: |
    # system wide configurations
    <system>
      log_level info
    </system>
    <source>
      @type kubernetes_metrics
      tag kube.*
      #node_name "#{ENV['SPLUNK_HEC_HOST']}"
      node_name "10.0.2.15"
      kubelet_port 10250
      use_rest_client_ssl true
      insecure_ssl true
      cluster_name minishift
    </source>
    <filter kube.**>
      @type record_modifier
      <record>
        metric_name ${tag}
        cluster_name minishift
      </record>
    </filter>
    <filter kube.node.**>
      @type record_modifier
      <record>
        source ${record['node']}
      </record>
    </filter>
    <filter kube.pod.**>
      @type record_modifier
      <record>
        source ${record['node']}/${record['pod-name']}
      </record>
    </filter>
    <filter kube.sys-container.**>
      @type record_modifier
      <record>
        source ${record['node']}/${record['pod-name']}/${record['name']}
      </record>
    </filter>
    <filter kube.container.**>
      @type record_modifier
      <record>
        source ${record['node']}/${record['pod-name']}/${record['container-name']}
      </record>
    </filter>
    <match kube.**>
      @type splunk_hec
      data_type metric
      metric_name_key metric_name
      metric_value_key value
      protocol https
      hec_host standalone 
      hec_port 8088
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      #host "#{ENV['SPLUNK_HEC_HOST']}"
      host "minishift"
      index cm_metrics
      source ${tag}
      insecure_ssl true 
      <buffer>
        chunk_limit_records 10000
      </buffer>
    </match>
