##---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sck-splunk-kubernetes-metrics
  labels:
    app: splunk-kubernetes-metrics
    chart: splunk-kubernetes-metrics-1.1.0
    release: sck
    heritage: Tiller
type: Opaque
data:
  splunk_hec_token: MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAw 
