##---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splunk-kubernetes-metrics
  labels:
    app: splunk-kubernetes-metrics
    chart: splunk-kubernetes-metrics-1.1.0
    release: sck
    heritage: Tiller