---
ansible_post_tasks: null
ansible_pre_tasks: null
config:
  baked: default.yml
  defaults_dir: /tmp/defaults
  env:
    headers: null
    var: SPLUNK_DEFAULTS_URL
    verify: true
  host:
    headers: null
    url: null
    verify: true
  max_delay: 60
  max_retries: 3
  max_timeout: 1200
hide_password: false
retry_num: 50
shc_bootstrap_delay: 30
splunk:
  admin_user: admin
  allow_upgrade: true
  app_paths:
    default: /opt/splunkforwarder/etc/apps
    deployment: /opt/splunkforwarder/etc/deployment-apps
    httpinput: /opt/splunkforwarder/etc/apps/splunk_httpinput
    idxc: /opt/splunkforwarder/etc/master-apps
    shc: /opt/splunkforwarder/etc/shcluster/apps
  enable_service: false
  exec: /opt/splunkforwarder/bin/splunk
  group: root
  hec_disabled: 0
  hec_enableSSL: 1
  hec_port: 8088
  hec_token: 80fb87e3-470c-4f1d-a1b2-3efa29f6a5c2
  home: /opt/splunkforwarder
  http_enableSSL: 0
  http_enableSSL_cert: null
  http_enableSSL_privKey: null
  http_enableSSL_privKey_password: null
  http_port: 8000
  ignore_license: false
  license_download_dest: /tmp/splunk.lic
  nfr_license: /tmp/nfr_enterprise.lic
  opt: /opt
  #password: 3/CBjNI3JEOlfsQE/LiIEysExRwgs58E
  pid: /opt/splunkforwarder/var/run/splunk/splunkd.pid
  s2s_enable: true
  s2s_port: 9997
  search_head_cluster_url: null
  secret: null
  smartstore: null
  svc_port: 8089
  tar_dir: splunkforwarder
  user: root
  wildcard_license: false
splunk_home_ownership_enforcement: false 

