##---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: splunk-kubernetes-logging
  name: splunk-kubernetes-logging

