---
apiVersion: v1
kind: Service
metadata:
  name: standalone 
  labels:
    app: splunk
    role: standalone
    tier: standalone
spec:
  type: LoadBalancer
  selector:
    app: splunk
    role: standalone
    tier: standalone
  ports:
    - name: splunkweb
      port: 8000 
      targetPort: 8000
    - name: splunkd
      port: 8089
      targetPort: 8089
    - name: s2s
      port: 9997
      targetPort: 9997
    - name: hec
      port: 8088
      targetPort: 8088


#apiVersion: v1
#kind: Service
#metadata:
#  name: search 
#  #namespace: splunk
#  labels:
#    app: splunk
#    tier: search 
#spec:
#  #type: LoadBalancer
#  selector:
#    app: splunk
#    role: splunk_search_head
#  ports:
#    - name: splunkweb
#      port: 80
#      targetPort: 8000
#    - name: splunkd
#      port: 8089
#      targetPort: 8089
