##---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sck-splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    chart: splunk-kubernetes-objects-1.1.0
    release: sck
    heritage: Tiller
data:
  fluent.conf: |
    <system>
      log_level info
    </system>
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "apps/v1"
      insecure_ssl true
      <pull>
        resource_name deployments
        interval 30s
      </pull>
      <pull>
        resource_name daemon_sets
        interval 30s
      </pull>
      <pull>
        resource_name replica_sets
        interval 30s
      </pull>
      <pull>
        resource_name stateful_sets
        interval 30s
      </pull>
    </source>
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "v1"
      insecure_ssl true
      <pull>
        resource_name pods
        interval 30s
      </pull>
      <pull>
        resource_name namespaces
        interval 30s
      </pull>
      <pull>
        resource_name nodes
        interval 30s
      </pull>
      <pull>
        resource_name services
        interval 30s
      </pull>
      <pull>
        resource_name config_maps
        interval 30s
      </pull>
      <pull>
        resource_name secrets
        interval 30s
      </pull>
      <pull>
        resource_name persistent_volumes
        interval 30s
      </pull>
      <pull>
        resource_name service_accounts
        interval 30s
      </pull>
      <pull>
        resource_name persistent_volume_claims
        interval 30s
      </pull>
      <pull>
        resource_name resource_quotas
        interval 30s
      </pull>
      <pull>
        resource_name component_statuses
        interval 30s
      </pull>
      <watch>
        resource_name events
      </watch>
    </source>

    <filter kube.**>
      @type jq_transformer
      # in ruby '\\' will escape and become just '\', since we need two '\' in the `gsub` jq filter, it becomes '\\\\'.
      jq '.record.source = "namespace:\(env.MY_NAMESPACE)/pod:\(env.MY_POD_NAME)" | .record.sourcetype = (.tag | gsub("\\\\."; ":")) | .record'
    </filter>

    <filter kube.**>
      @type jq_transformer
      jq '.record.cluster_name = "openshift" | .record'
    </filter>

    <match kube.**>
      @type splunk_hec
      protocol https
      hec_host standalone 
      hec_port 8088
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      host "#{ENV['SPLUNK_HEC_HOST']}"
      source_key source
      sourcetype_key sourcetype
      index cm_meta
      insecure_ssl true
      <fields>
        cluster_name
      </fields>
      <buffer>
        @type memory
        chunk_limit_records 10000
        chunk_limit_size 200m
        flush_interval 3s
        flush_thread_count 1
        overflow_action block
        retry_max_times 3
        total_limit_size 600m
      </buffer>
    </match>
