##---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sck-splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    chart: splunk-kubernetes-objects-1.1.0
    release: sck
    heritage: Tiller
type: Opaque
data:
  splunk_hec_token: MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAw 
