##---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    chart: splunk-kubernetes-objects-1.1.0
    release: sck
    heritage: Tiller