---
apiVersion: v1
kind: Service
metadata:
  name: buttercupgo 
  labels:
    app: buttercupgo
spec:
  selector:
    app: buttercupgo
  ports:
    - name: web
      port: 3040 
      targetPort: 3040 
    - name: port2 
      port: 3000
      targetPort: 3000
  clusterIP: None
